run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - gofumpt
    - goimports
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - gosec
  disable: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
