run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - unconvert
    - unparam
    - gocyclo
    - gofumpt
  disable:
    - gosec
    - exportloopref
